server:
    port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
#maybe will need change this value on default=30 in production
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.springframework: INFO
