server:
    port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  rabbitmq:
    host: rabbitmq

logging:
  level:
    org.springframework: INFO
