server:
    port: 9020

spring:
  application:
    name: thinkclearly-account-service
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_ACCOUNT_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    initial-size: 5
    max-active: 100
    max-idle: 5
    test-on-borrow: true
    test-while-idle: true
    test-on-return: true
    min-idle: 2
    validation-query: select 1
  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}
  sleuth:
    sampler:
      percentage: 0.9

liquibase:
  change-log: classpath:db-changelog.xml

eureka:
  client:
    serviceUrl:
      defaultZone: ${REGISTRY_SERVICE_HOST}/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

auth:
  service:
    sign:
      key: ${SECRET_KEY}

logging:
  level:
    org.springframework: INFO
