server:
  port: 8787

turbine:
  stream:
    port: 8989

spring:
  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}

logging:
  level:
    org.springframework: INFO